import = [
    "~/.config/alacritty/themes/themes/{github_dark_dimmed}.toml"
]

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
size = 14.0

[keyboard]
bindings = [
  { key = "i", mods = "Control", action = "ClearLogNotice" },
  { key = "r", mode = "Vi|~Search", action = "ToggleViMode" },
]
